services:
  # Backend Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: flake-wire-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATA_DIR=/app/data
    env_file:
      - .env
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - flake-wire-network
    volumes:
      - ./logs:/app/logs
      - flake-wire-data:/app/data
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  # Frontend Service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: flake-wire-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - flake-wire-network
    security_opt:
      - no-new-privileges:true

networks:
  flake-wire-network:
    driver: bridge
    name: flake-wire-network

volumes:
  logs:
    driver: local
  flake-wire-data:
    driver: local
